### ISSUE TITLE
Use Admin Framework from CounterStrikeSharp

### ISSUE THREAD

**Issue by kus** [LordFetznschaedl/CS2Rcon#1]
CounterStrikeSharp has introduced an [Admin Framework](https://docs.cssharp.dev/features/admin-framework/) which supports admins and flags similar to SourceMod, removing the need to have an admin file for every plugin.

Could you please update your plugin to use this new system so we don't have to have an individual admin file for your plugin.

**Comment by LordFetznschaedl** [comment]
Hello. Thank you for your message.
This change is on the roadmap for the next few days. 
It will most likely happen today or tomorrow.

**Comment by LordFetznschaedl** [comment]
Hello @kus,
Plugin has been updated to use the new Admin Framework. The needed permission is `@css/rcon`.
https://github.com/LordFetznschaedl/CS2Rcon/releases/tag/latest
Thank you :)
