### ISSUE TITLE
Windows Only?

### ISSUE THREAD

**Issue by 0aShadow** [LordFetznschaedl/CS2Rcon#4]
Am I right when I say this plugin is only available for windows?

**Comment by LordFetznschaedl** [comment]
Plugin is verified to work on Linux but should also work on Windows.

**Comment by 0aShadow** [comment]
So there is a DLL file inside the folder, DLL Files can be loaded in Linux?

**Comment by LordFetznschaedl** [comment]
Yes. Just load it into a subfolder called CS2Rcon in the plugin folder of CounterStrikeSharp.

**Comment by 0aShadow** [comment]
Works perfectly fine!
Thx, there is no issue. I just was not that smart 😄
